using System.Text.RegularExpressions;

namespace Tenebit.Application.Common;

/// <summary>
/// Resolves a stable, machine-readable error code for each distinct business-error message produced
/// across the application (via <see cref="Error"/> factory methods and <see cref="DomainException"/>).
/// Audit P2 #7: previously every <c>Error.Validation(...)</c>/<c>NotFound(...)</c>/<c>Conflict(...)</c>
/// call collapsed to one generic code per HTTP-status category (VALIDATION_ERROR/NOT_FOUND/CONFLICT),
/// so a frontend (or any API consumer) could only distinguish error causes by matching the translated
/// message text - fragile and language-dependent.
///
/// This mirrors <see cref="ErrorMessageTranslator"/>'s approach: the Polish message is the canonical
/// key (source of truth stays "write a plain Polish message" at the call site), and this lookup layer
/// maps it to a stable code without touching the ~220 call sites across the Application/Domain layers.
/// A message not found here falls back to the generic per-status code (see <see cref="Error"/>), so
/// nothing breaks if a call site's message isn't (yet) listed.
/// </summary>
public static class ErrorCodeResolver
{
    private static readonly Dictionary<string, string> ExactCodes = new()
    {
        ["Aby przejść na plan Pro, użyj płatności Stripe (checkout)."] = "SUBSCRIPTION_USE_STRIPE_CHECKOUT",
        ["Adres e-mail uczestnika jest wymagany."] = "AUDIT_PARTICIPANT_EMAIL_REQUIRED",
        ["Aktywo nie istnieje."] = "ASSET_NOT_FOUND",
        ["Aktywo nie jest dostępne do wydania."] = "ASSET_NOT_AVAILABLE_FOR_ASSIGNMENT",
        ["Akceptacja regulaminu i polityki prywatności jest wymagana."] = "AUTH_LEGAL_ACCEPTANCE_REQUIRED",
        ["Anulować można tylko wniosek przed wydaniem sprzętu."] = "RESERVATION_CANCEL_INVALID_STATE",
        ["Brak adresu e-mail dla zalogowanego użytkownika."] = "AUTH_USER_EMAIL_MISSING",
        ["Brak oczekującej kontroli dla tego aktywa."] = "ASSET_INSPECTION_NOT_PENDING",
        ["Brak wolnych miejsc w tej licencji."] = "LICENSE_NO_FREE_SEATS",
        ["Brak wpisu manifestu dla przesłanego pliku."] = "EVIDENCE_MANIFEST_ENTRY_MISSING",
        ["Cel rezerwacji jest wymagany."] = "RESERVATION_PURPOSE_REQUIRED",
        ["Cena zakupu nie może być ujemna."] = "ASSET_PURCHASE_PRICE_NEGATIVE",
        ["Co najmniej jedno aktywo nie jest dostępne do wydania."] = "ASSIGNMENT_ASSET_NOT_AVAILABLE",
        ["Cooldown musi być w zakresie 0–14 dni."] = "ALERT_COOLDOWN_OUT_OF_RANGE",
        ["Data rozpoczęcia rezerwacji nie może być w przeszłości."] = "RESERVATION_START_IN_PAST",
        ["Data zakończenia musi być późniejsza niż data rozpoczęcia."] = "RESERVATION_END_BEFORE_START",
        ["Dla digestu tygodniowego konieczny jest dzień tygodnia."] = "ALERT_DIGEST_WEEKDAY_REQUIRED",
        ["Dla tej osoby istnieje już aktywna sprawa offboardingowa."] = "OFFBOARDING_CASE_ALREADY_ACTIVE",
        ["Dodaj co najmniej jedno aktywo do wydania."] = "ASSIGNMENT_AT_LEAST_ONE_ASSET_REQUIRED",
        ["Dodaj co najmniej jedno zdjęcie."] = "EVIDENCE_AT_LEAST_ONE_PHOTO_REQUIRED",
        ["Dostawca logowania nie udostępnił adresu e-mail. Wyraź zgodę na udostępnienie e-maila i spróbuj ponownie."] = "AUTH_OAUTH_EMAIL_NOT_SHARED",
        ["Dozwolone są tylko zdjęcia w formacie JPEG, PNG lub WebP."] = "EVIDENCE_UNSUPPORTED_IMAGE_FORMAT",
        ["Dwuskładnikowe uwierzytelnianie nie jest włączone."] = "AUTH_TWO_FACTOR_NOT_ENABLED",
        ["E-mail z tego dostawcy nie jest zweryfikowany. Zaloguj się hasłem i połącz konto w ustawieniach."] = "AUTH_OAUTH_EMAIL_NOT_VERIFIED",
        ["Etykieta pola własnego jest wymagana."] = "ASSET_CATEGORY_FIELD_LABEL_REQUIRED",
        ["Etykieta statusu jest wymagana."] = "ASSET_STATUS_LABEL_REQUIRED",
        ["Godziny cichego trybu muszą być ustawione razem."] = "ALERT_QUIET_HOURS_BOTH_REQUIRED",
        ["Godziny ciszy wymagają obu wartości: początku i końca."] = "PRIVACY_QUIET_HOURS_BOTH_REQUIRED",
        ["Hash tokenu jest wymagany."] = "TOKEN_HASH_REQUIRED",
        ["Hasło musi mieć co najmniej 8 znaków."] = "AUTH_PASSWORD_TOO_SHORT",
        ["Identyfikator organizacji jest wymagany."] = "ORGANIZATION_ID_REQUIRED",
        ["Imię i nazwisko są wymagane."] = "PERSON_NAME_REQUIRED",
        ["Kampania nie istnieje."] = "AUDIT_CAMPAIGN_NOT_FOUND",
        ["Kampanię można edytować tylko w statusie roboczym."] = "AUDIT_CAMPAIGN_EDIT_INVALID_STATE",
        ["Kampanię można uruchomić tylko ze statusu roboczego."] = "AUDIT_CAMPAIGN_START_INVALID_STATE",
        ["Kampanię można zakończyć tylko ze statusu aktywnego albo w przeglądzie."] = "AUDIT_CAMPAIGN_COMPLETE_INVALID_STATE",
        ["Kategoria nie istnieje."] = "ASSET_CATEGORY_NOT_FOUND",
        ["Kategoria o tej nazwie już istnieje."] = "ASSET_CATEGORY_NAME_EXISTS",
        ["Klucz pola własnego jest wymagany."] = "ASSET_CATEGORY_FIELD_KEY_REQUIRED",
        ["Klucze pól własnych muszą być unikalne w obrębie kategorii."] = "ASSET_CATEGORY_FIELD_KEY_DUPLICATE",
        ["Kolor tekstu statusu musi być w formacie szesnastkowym, np. #1d4ed8."] = "ASSET_STATUS_TEXT_COLOR_INVALID",
        ["Kolor tła statusu musi być w formacie szesnastkowym, np. #eff6ff."] = "ASSET_STATUS_BACKGROUND_COLOR_INVALID",
        ["Kontrola nie istnieje."] = "ASSET_INSPECTION_NOT_FOUND",
        ["Kontrola tego aktywa została już zakończona."] = "ASSET_INSPECTION_ALREADY_COMPLETED",
        ["Koszt końcowy nie może być ujemny."] = "SERVICE_TICKET_FINAL_COST_NEGATIVE",
        ["Licencja nie istnieje."] = "LICENSE_NOT_FOUND",
        ["Liczba miejsc nie może być ujemna."] = "LICENSE_SEATS_NEGATIVE",
        ["Kod resetujący jest nieprawidłowy lub wygasł."] = "AUTH_PASSWORD_RESET_CODE_INVALID",
        ["Link jest nieprawidłowy lub wygasł."] = "PUBLIC_LINK_INVALID_OR_EXPIRED",
        ["Kod weryfikacyjny jest nieprawidłowy lub wygasł."] = "AUTH_EMAIL_VERIFICATION_CODE_INVALID",
        ["Lokalizacja nadrzędna nie istnieje."] = "LOCATION_PARENT_NOT_FOUND",
        ["Lokalizacja nie istnieje."] = "LOCATION_NOT_FOUND",
        ["Lokalizacja nie może być nadrzędna sama dla siebie."] = "LOCATION_SELF_PARENT",
        ["Materiał dowodowy nie istnieje."] = "EVIDENCE_NOT_FOUND",
        ["Najpierw usuń podlokalizacje tej pozycji."] = "LOCATION_HAS_CHILDREN",
        ["Najpierw wygeneruj sekret 2FA."] = "AUTH_TWO_FACTOR_SECRET_NOT_GENERATED",
        ["Nazwa aktywa jest wymagana."] = "ASSET_NAME_REQUIRED",
        ["Nazwa firmy jest wymagana."] = "ORGANIZATION_NAME_REQUIRED",
        ["Nazwa kampanii jest wymagana."] = "AUDIT_CAMPAIGN_NAME_REQUIRED",
        ["Nazwa kategorii jest wymagana."] = "ASSET_CATEGORY_NAME_REQUIRED",
        ["Nazwa licencji jest wymagana."] = "LICENSE_NAME_REQUIRED",
        ["Nazwa lokalizacji jest wymagana."] = "LOCATION_NAME_REQUIRED",
        ["Nazwa pliku jest wymagana."] = "FILE_NAME_REQUIRED",
        ["Nazwa pozycji jest wymagana."] = "RESERVATION_ITEM_NAME_REQUIRED",
        ["Nazwa typu relacji jest wymagana."] = "RELATION_TYPE_NAME_REQUIRED",
        ["Nazwa zespołu jest wymagana."] = "TEAM_NAME_REQUIRED",
        ["Nazwa zestawu stanowiskowego jest wymagana."] = "JOB_PROFILE_NAME_REQUIRED",
        ["Nie możesz odłączyć jedynego sposobu logowania. Ustaw najpierw hasło."] = "AUTH_CANNOT_UNLINK_ONLY_LOGIN_METHOD",
        ["Nie można anulować offboardingu po dezaktywacji osoby."] = "OFFBOARDING_CANNOT_CANCEL_AFTER_DEACTIVATION",
        ["Nie można anulować zakończonej kampanii."] = "AUDIT_CAMPAIGN_CANNOT_CANCEL_COMPLETED",
        ["Nie można anulować zakończonej sprawy."] = "OFFBOARDING_CANNOT_CANCEL_COMPLETED",
        ["Nie można edytować opublikowanej procedury - osoby już ją zaakceptowały. Zarchiwizuj ją i utwórz nową wersję."] = "PROCEDURE_CANNOT_EDIT_PUBLISHED",
        ["Nie można modyfikować wydania, które zostało już podpisane lub zamknięte."] = "ASSIGNMENT_CANNOT_MODIFY_SIGNED_OR_CLOSED",
        ["Nie można opublikować procedury bez pliku."] = "PROCEDURE_CANNOT_PUBLISH_WITHOUT_FILE",
        ["Nie można opublikować zarchiwizowanej procedury."] = "PROCEDURE_CANNOT_PUBLISH_ARCHIVED",
        ["Nie można ustawić liczby miejsc poniżej liczby już przypisanych."] = "LICENSE_SEATS_BELOW_ASSIGNED",
        ["Nie można usunąć aktywa powiązanego z wydaniami, kontrolami, zgłoszeniami serwisowymi, rezerwacjami lub offboardingiem."] = "ASSET_IN_USE",
        ["Nie można ustawić lokalizacji podrzędnej jako nadrzędnej - utworzyłoby to cykl."] = "LOCATION_CYCLE_DETECTED",
        ["Nie można usunąć kategorii używanej przez aktywa lub zestawy."] = "ASSET_CATEGORY_IN_USE",
        ["Nie można usunąć lokalizacji z przypisanymi aktywami albo osobami."] = "LOCATION_IN_USE",
        ["Nie można usunąć pracownika, bo ma przypisany sprzęt, historię wydań albo jest przełożonym. Najpierw zwróć sprzęt albo usuń powiązania."] = "PERSON_IN_USE",
        ["Nie można usunąć typu relacji przypisanego do osób."] = "RELATION_TYPE_IN_USE",
        ["Nie można usunąć zespołu przypisanego do osób lub aktywów."] = "TEAM_IN_USE",
        ["Nie można wydać pozycji bez przydzielonego aktywa."] = "RESERVATION_ITEM_NO_ASSET_ASSIGNED",
        ["Nie można zamienić pozycji bez przydzielonego aktywa."] = "RESERVATION_ITEM_SWAP_NO_ASSET",
        ["Nie można zamknąć sprawy przed zaplanowaną dezaktywacją osoby."] = "OFFBOARDING_CANNOT_COMPLETE_BEFORE_DEACTIVATION",
        ["Nie można zamknąć sprawy z nierozliczonymi wymaganymi pozycjami."] = "OFFBOARDING_UNRESOLVED_REQUIRED_ITEMS",
        ["Nie można zmienić odpowiedzi pracownika po rozliczeniu pozycji."] = "OFFBOARDING_ITEM_ALREADY_RESOLVED",
        ["Nie można zmienić statusu zamkniętego zgłoszenia serwisowego."] = "SERVICE_TICKET_CLOSED_STATUS_LOCKED",
        ["Nie można zwrócić aktywa dla anulowanego wydania."] = "ASSIGNMENT_CANNOT_RETURN_CANCELLED",
        ["Nie można zwrócić wydania, które zostało już zamknięte lub anulowane."] = "ASSIGNMENT_RETURN_INVALID_STATE",
        ["Nie znaleziono konta powiązanego z tym linkiem."] = "AUTH_ACCOUNT_NOT_LINKED",
        ["Nie znaleziono konta."] = "AUTH_ACCOUNT_NOT_FOUND",
        ["Nie znaleziono organizacji powiązanej z kontem."] = "AUTH_ORGANIZATION_NOT_FOUND",
        ["Niektóre aktywa nie istnieją."] = "ASSET_SOME_NOT_FOUND",
        ["Niektóre procedury nie istnieją."] = "PROCEDURE_SOME_NOT_FOUND",
        ["Nieobsługiwany preferowany język."] = "PERSON_LANGUAGE_UNSUPPORTED",
        ["Nieprawidłowy e-mail lub hasło."] = "AUTH_INVALID_CREDENTIALS",
        ["Nieprawidłowy kod uwierzytelniający."] = "AUTH_INVALID_TWO_FACTOR_CODE",
        ["Nieprawidłowy kod. Sprawdź godzinę na urządzeniu i spróbuj ponownie."] = "AUTH_INVALID_TOTP_CODE",
        ["Nieprawidłowy lub uszkodzony plik obrazu."] = "EVIDENCE_IMAGE_CORRUPTED",
        ["Nieprawidłowy podpis webhooka Stripe."] = "SUBSCRIPTION_INVALID_STRIPE_SIGNATURE",
        ["Nieprawidłowy status docelowy aktywa po zamknięciu zgłoszenia serwisowego."] = "SERVICE_TICKET_INVALID_TARGET_ASSET_STATUS",
        ["Nieprawidłowy zakres kampanii."] = "AUDIT_CAMPAIGN_INVALID_SCOPE",
        ["Nowe wydanie można utworzyć tylko dla aktywnej osoby."] = "ASSIGNMENT_PERSON_NOT_ACTIVE",
        ["Nowy termin musi być późniejszy niż obecny."] = "DUE_DATE_MUST_BE_LATER",
        ["Nowy właściciel jest wymagany dla tego rozstrzygnięcia."] = "AUDIT_NEW_OWNER_REQUIRED",
        ["Numer wydania jest wymagany."] = "PROTOCOL_NUMBER_REQUIRED",
        ["Odpowiedzi zostały już wysłane i nie można ich zmienić."] = "AUDIT_RESPONSES_ALREADY_SUBMITTED_LOCKED",
        ["Odpowiedzi zostały już wysłane."] = "AUDIT_RESPONSES_ALREADY_SUBMITTED",
        ["Odrzucić można tylko wniosek oczekujący na akceptację."] = "RESERVATION_REJECT_INVALID_STATE",
        ["Offboarding można rozpocząć tylko dla aktywnej osoby."] = "OFFBOARDING_PERSON_NOT_ACTIVE",
        ["Offboarding można uruchomić tylko ze statusu roboczego."] = "OFFBOARDING_START_INVALID_STATE",
        ["Okres przechowywania adresu IP jest wymagany, gdy przechwytywanie adresu IP jest włączone."] = "PRIVACY_IP_RETENTION_REQUIRED",
        ["Okres przechowywania materiału dowodowego musi być większy od zera."] = "PRIVACY_EVIDENCE_RETENTION_MUST_BE_POSITIVE",
        ["Organizacja ma już aktywną płatną subskrypcję."] = "SUBSCRIPTION_ALREADY_ACTIVE_PAID",
        ["Organizacja nie istnieje."] = "ORGANIZATION_NOT_FOUND",
        ["Organizacja nie ma jeszcze konta rozliczeniowego Stripe."] = "SUBSCRIPTION_NO_STRIPE_ACCOUNT",
        ["Osiągnięto limit 5 zdjęć dla tego aktywa i etapu."] = "EVIDENCE_PHOTO_LIMIT_REACHED",
        ["Osoba nie istnieje."] = "PERSON_NOT_FOUND",
        ["Osoba nie ma adresu e-mail - nie można wysłać linku."] = "PERSON_EMAIL_MISSING_FOR_LINK",
        ["Osoba nie może być swoim własnym przełożonym."] = "PERSON_CANNOT_BE_OWN_MANAGER",
        ["Osoba odstępująca jest wymagana."] = "WAIVING_PERSON_REQUIRED",
        ["Osoba przypisana do sprawy nie istnieje."] = "OFFBOARDING_ASSIGNED_PERSON_NOT_FOUND",
        ["Osoba rozstrzygająca jest wymagana."] = "RESOLVING_PERSON_REQUIRED",
        ["Osoba z tym adresem e-mail już istnieje."] = "PERSON_EMAIL_EXISTS",
        ["Pakiet onboardingowy można utworzyć tylko dla aktywnej osoby."] = "ONBOARDING_PERSON_NOT_ACTIVE",
        ["Plik nie jest prawidłowym obrazem JPEG/PNG/WebP."] = "EVIDENCE_INVALID_IMAGE_FILE",
        ["Plik procedury jest pusty."] = "PROCEDURE_FILE_EMPTY",
        ["Plik procedury może mieć maksymalnie 25 MB."] = "PROCEDURE_FILE_TOO_LARGE",
        ["Plik procedury nie istnieje."] = "PROCEDURE_FILE_NOT_FOUND",
        ["Pole nie jest polem wrażliwym."] = "ASSET_FIELD_NOT_SENSITIVE",
        ["Ponowne otwarcie jest możliwe tylko dla wysłanych odpowiedzi."] = "AUDIT_REOPEN_INVALID_STATE",
        ["Poprawny adres e-mail jest wymagany."] = "EMAIL_REQUIRED",
        ["Poprawny e-mail użytkownika jest wymagany."] = "USER_EMAIL_REQUIRED",
        ["Powód anulowania jest wymagany."] = "CANCELLATION_REASON_REQUIRED",
        ["Powód odrzucenia jest wymagany."] = "REJECTION_REASON_REQUIRED",
        ["Powód odstąpienia jest wymagany."] = "WAIVER_REASON_REQUIRED",
        ["Powód zamiany jest wymagany."] = "SWAP_REASON_REQUIRED",
        ["Pozycja jest już rozliczona i nie można jej zamienić."] = "RESERVATION_ITEM_ALREADY_RESOLVED_CANNOT_SWAP",
        ["Pozycja jest już rozliczona."] = "ITEM_ALREADY_RESOLVED",
        ["Pozycja jest już rozstrzygnięta."] = "ITEM_ALREADY_DECIDED",
        ["Pozycja nie istnieje."] = "ITEM_NOT_FOUND",
        ["Pozycje wniosku można edytować tylko w statusie roboczym."] = "RESERVATION_ITEMS_EDIT_INVALID_STATE",
        ["Pracownik nie istnieje."] = "PERSON_NOT_FOUND",
        ["Pracownik z tym adresem e-mail już istnieje."] = "PERSON_EMAIL_EXISTS",
        ["Procedura nie istnieje."] = "PROCEDURE_NOT_FOUND",
        ["Przejście do statusu Completed lub Cancelled wymaga metody Complete() lub Cancel()."] = "RESERVATION_STATUS_TRANSITION_INVALID",
        ["Przydzielić można tylko pozycję oczekującą."] = "RESERVATION_ITEM_ASSIGN_INVALID_STATE",
        ["Przywrócenie zatrudnienia dotyczy tylko spraw po dezaktywacji osoby."] = "OFFBOARDING_RESTORE_INVALID_STATE",
        ["Płatności Stripe nie są jeszcze skonfigurowane."] = "SUBSCRIPTION_STRIPE_NOT_CONFIGURED",
        ["Rozstrzygnięcie musi być inne niż None."] = "AUDIT_RESOLUTION_REQUIRED",
        ["Sesja wygasła. Zaloguj się ponownie."] = "AUTH_SESSION_EXPIRED",
        ["Sprawa offboardingowa nie istnieje."] = "OFFBOARDING_CASE_NOT_FOUND",
        ["Sprawę offboardingową można edytować tylko w statusie roboczym."] = "OFFBOARDING_EDIT_INVALID_STATE",
        ["Sprawę offboardingową można utworzyć tylko dla aktywnej osoby."] = "OFFBOARDING_PERSON_NOT_ACTIVE",
        ["Suma kontrolna pliku jest wymagana."] = "FILE_CHECKSUM_REQUIRED",
        ["Szacowany koszt nie może być ujemny."] = "SERVICE_TICKET_ESTIMATED_COST_NEGATIVE",
        ["Ta akceptacja procedury została już zarejestrowana i nie może zostać zmieniona."] = "PROCEDURE_ACCEPTANCE_ALREADY_RECORDED",
        ["Ta organizacja ma aktywną płatną subskrypcję. Zarządzaj nią (w tym anulowaniem) w portalu rozliczeń Stripe."] = "SUBSCRIPTION_MANAGE_VIA_STRIPE_PORTAL",
        ["Ta osoba ma już przypisane miejsce w tej licencji."] = "LICENSE_SEAT_ALREADY_ASSIGNED",
        ["Ta pozycja nie dotyczy aktywa."] = "ITEM_NOT_ASSET_TYPE",
        ["Ta pozycja nie dotyczy zwolnienia licencji."] = "ITEM_NOT_LICENSE_RELEASE_TYPE",
        ["Ta pozycja nie dotyczy zwrotu aktywa."] = "ITEM_NOT_ASSET_RETURN_TYPE",
        ["Tag aktywa jest już używany."] = "ASSET_TAG_EXISTS",
        ["Tag aktywa jest wymagany."] = "ASSET_TAG_REQUIRED",
        ["Ten asset jest już dodany do wydania."] = "ASSIGNMENT_ASSET_ALREADY_ADDED",
        ["Ten status wymaga jawnego rozstrzygnięcia (Missing, Damaged albo Retained)."] = "AUDIT_STATUS_REQUIRES_RESOLUTION",
        ["To aktywo nie należy do tego wydania."] = "ASSIGNMENT_ASSET_NOT_IN_ASSIGNMENT",
        ["To aktywo zostało już zgłoszone niedawno. Spróbuj ponownie później."] = "ASSET_REPORT_RATE_LIMITED",
        // All three public-report limits answer with one code: the caller is an anonymous member of the
        // public and only needs "not now", while the wording tells them which situation they are in.
        ["To aktywo zostało już przez Ciebie zgłoszone niedawno. Spróbuj ponownie później."] = "ASSET_REPORT_RATE_LIMITED",
        ["To aktywo zostało już zgłoszone wielokrotnie. Zgłoszenie dotarło do administratorów."] = "ASSET_REPORT_RATE_LIMITED",
        ["Zbyt wiele zgłoszeń w krótkim czasie. Spróbuj ponownie później."] = "ASSET_REPORT_RATE_LIMITED",
        ["To konto nie jest połączone z tym dostawcą."] = "AUTH_ACCOUNT_NOT_LINKED_TO_PROVIDER",
        ["To samo aktywo nie może wystąpić dwa razy w jednym wydaniu."] = "ASSIGNMENT_DUPLICATE_ASSET",
        ["Treść zgłoszenia jest wymagana."] = "REPORT_CONTENT_REQUIRED",
        ["Tylko wydane aktywo można oznaczyć jako oczekujące na zwrot."] = "ASSET_MARK_PENDING_RETURN_INVALID_STATE",
        ["Typ relacji nie istnieje."] = "RELATION_TYPE_NOT_FOUND",
        ["Typ relacji o tej nazwie już istnieje."] = "RELATION_TYPE_NAME_EXISTS",
        ["Tytuł procedury jest wymagany."] = "PROCEDURE_TITLE_REQUIRED",
        ["Uczestnik nie istnieje."] = "AUDIT_PARTICIPANT_NOT_FOUND",
        ["Układ pulpitu nie może być pusty."] = "DASHBOARD_LAYOUT_EMPTY",
        ["Uzasadnienie jest wymagane dla tego rozstrzygnięcia."] = "AUDIT_RESOLUTION_NOTES_REQUIRED",
        ["Uzasadnienie jest wymagane."] = "JUSTIFICATION_REQUIRED",
        ["Uzupełnij wymagane pola pakietu startowego."] = "JOB_PROFILE_REQUIRED_FIELDS_MISSING",
        ["Użytkownik nie istnieje."] = "USER_NOT_FOUND",
        ["Użytkownik tworzący jest wymagany."] = "CREATING_USER_REQUIRED",
        ["Użytkownik z tym adresem e-mail już istnieje."] = "USER_EMAIL_EXISTS",
        ["Vendor zgłoszenia serwisowego jest wymagany."] = "SERVICE_TICKET_VENDOR_REQUIRED",
        ["Wersja procedury jest wymagana."] = "PROCEDURE_VERSION_REQUIRED",
        ["Wniosek można edytować tylko w statusie roboczym."] = "RESERVATION_EDIT_INVALID_STATE",
        ["Wniosek można złożyć tylko ze statusu roboczego."] = "RESERVATION_SUBMIT_INVALID_STATE",
        ["Wniosek musi zawierać co najmniej jedną pozycję."] = "RESERVATION_AT_LEAST_ONE_ITEM_REQUIRED",
        ["Wszystkie pozycje muszą mieć przydzielone aktywo przed wydaniem."] = "RESERVATION_ITEMS_MUST_HAVE_ASSET_BEFORE_ISSUE",
        ["Wybrana inspekcja aktywa nie istnieje."] = "SERVICE_TICKET_INSPECTION_NOT_FOUND",
        ["Wybrana kategoria nie istnieje."] = "ASSET_CATEGORY_NOT_FOUND",
        ["Wybrana osoba nie istnieje."] = "PERSON_NOT_FOUND",
        ["Wybrany domyślny przełożony nie istnieje."] = "JOB_PROFILE_DEFAULT_MANAGER_NOT_FOUND",
        ["Wybrany nowy właściciel nie istnieje."] = "AUDIT_NEW_OWNER_NOT_FOUND",
        ["Wybrany pracownik nie istnieje."] = "PERSON_NOT_FOUND",
        ["Wybrany przełożony nie istnieje."] = "MANAGER_NOT_FOUND",
        ["Wybrany właściciel procesu nie istnieje."] = "OFFBOARDING_PROCESS_OWNER_NOT_FOUND",
        ["Wybrany zespół nie istnieje."] = "TEAM_NOT_FOUND",
        ["Wybrany zestaw stanowiskowy nie istnieje."] = "JOB_PROFILE_NOT_FOUND",
        ["Wydanie można zaakceptować tylko wtedy, gdy oczekuje na akceptację albo jest po terminie."] = "ASSIGNMENT_ACCEPT_INVALID_STATE",
        ["Wydanie nie istnieje."] = "ASSIGNMENT_NOT_FOUND",
        ["Wydać sprzęt można tylko z zatwierdzonego wniosku gotowego do odbioru."] = "RESERVATION_ISSUE_INVALID_STATE",
        ["Wymagana ilość musi być większa od zera."] = "QUANTITY_MUST_BE_POSITIVE",
        ["Za mało danych historycznych do porównania - migawki zbierają się od teraz, spróbuj ponownie za kilka dni."] = "DASHBOARD_INSUFFICIENT_HISTORY",
        ["Zablokowany materiał dowodowy nie może zostać usunięty."] = "EVIDENCE_LOCKED_CANNOT_DELETE",
        ["Zakończyć można tylko wydaną rezerwację."] = "RESERVATION_COMPLETE_INVALID_STATE",
        ["Zamkniętego zgłoszenia serwisowego nie można edytować."] = "SERVICE_TICKET_CLOSED_CANNOT_EDIT",
        ["Zatwierdzić można tylko wniosek oczekujący na akceptację."] = "RESERVATION_APPROVE_INVALID_STATE",
        ["Zdjęcie dotyczy aktywa spoza wydania."] = "EVIDENCE_ASSET_NOT_IN_ASSIGNMENT",
        ["Zdjęcie jest puste."] = "EVIDENCE_PHOTO_EMPTY",
        ["Zdjęcie może mieć maksymalnie 5 MB."] = "EVIDENCE_PHOTO_TOO_LARGE",
        ["Zespół nie istnieje."] = "TEAM_NOT_FOUND",
        ["Zespół o tej nazwie już istnieje."] = "TEAM_NAME_EXISTS",
        ["Zestaw stanowiskowy nie istnieje."] = "JOB_PROFILE_NOT_FOUND",
        ["Zestaw stanowiskowy nie zawiera żadnego dostępnego aktywa - dodaj aktywo ręcznie."] = "JOB_PROFILE_NO_AVAILABLE_ASSET",
        ["Zestaw stanowiskowy o tej nazwie już istnieje."] = "JOB_PROFILE_NAME_EXISTS",
        ["Zestaw zawiera kategorię, która nie istnieje."] = "JOB_PROFILE_CATEGORY_NOT_FOUND",
        ["Zestaw zawiera procedurę, która nie istnieje."] = "JOB_PROFILE_PROCEDURE_NOT_FOUND",
        ["Zgłoszenie serwisowe nie istnieje."] = "SERVICE_TICKET_NOT_FOUND",
        ["Zgłoszenie serwisowe zostało już zamknięte."] = "SERVICE_TICKET_ALREADY_CLOSED",
        ["Zutylizowane aktywo nie może wrócić do obiegu."] = "ASSET_DISPOSED_CANNOT_RETURN_TO_CIRCULATION",
        ["Zutylizowanego aktywa nie można przypisać."] = "ASSET_DISPOSED_CANNOT_ASSIGN",
    };

    private static readonly List<(Regex Pattern, string Code)> TemplateCodes = new()
    {
        (new Regex(@"^Limit aktywów przekroczony\."), "SUBSCRIPTION_ASSET_LIMIT_EXCEEDED"),
        // Pozostałe zasoby dzielą limit planu z aktywami (OrganizationSubscription.GetResourceLimit) i
        // muszą dawać klientowi ten sam, rozpoznawalny kod - inaczej import CSV nie odróżni wyczerpanego
        // limitu od zwykłego błędu walidacji wiersza i próbowałby dalej dla każdego kolejnego wiersza.
        (new Regex(@"^Limit [\p{L} ]+ przekroczony\. Plan .+ pozwala na \d+ [\p{L} ]+\. Przejdź na wyższy plan\.$"), "SUBSCRIPTION_RESOURCE_LIMIT_EXCEEDED"),
        (new Regex(@"^Limit planu .+ \(\d+\) został osiągnięty "), "SUBSCRIPTION_RESOURCE_LIMIT_EXCEEDED"),
        (new Regex(@"^Nieznana rola: "), "ROLE_UNKNOWN"),
        (new Regex(@"^Nieznane uprawnienie: "), "PERMISSION_UNKNOWN"),
        (new Regex(@"^Nieznany status aktywa: "), "ASSET_STATUS_UNKNOWN"),
        (new Regex("^Pole „.+” jest wymagane\\.$"), "FIELD_REQUIRED"),
        (new Regex(@"^Unknown plan: "), "SUBSCRIPTION_PLAN_UNKNOWN"),
    };

    public static string? Resolve(string message)
    {
        if (string.IsNullOrWhiteSpace(message))
        {
            return null;
        }

        if (ExactCodes.TryGetValue(message, out var code))
        {
            return code;
        }

        foreach (var (pattern, templateCode) in TemplateCodes)
        {
            if (pattern.IsMatch(message))
            {
                return templateCode;
            }
        }

        return null;
    }
}
