import {
  Antenna,
  Armchair,
  Badge,
  Barcode,
  BatteryCharging,
  Battery,
  Box,
  Briefcase,
  Cable,
  Camera,
  Car,
  Cloud,
  CreditCard,
  FileSignature,
  FileText,
  Fuel,
  Glasses,
  Globe,
  HardDrive,
  HardHat,
  Headphones,
  IdCard,
  Key,
  Keyboard,
  Lamp,
  Laptop,
  Lock,
  Mail,
  Mic,
  Monitor,
  Mouse,
  Network,
  ParkingSquare,
  Package,
  PlugZap,
  Presentation,
  Printer,
  Projector,
  Receipt,
  Router,
  ScanLine,
  ScrollText,
  Server,
  Shield,
  ShieldCheck,
  Smartphone,
  Speaker,
  Tablet,
  Tv,
  Usb,
  Users,
  Video,
  Watch,
  Webcam,
  Wifi,
  Wrench,
  Zap
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export const categoryIconOptions: { value: string; icon: LucideIcon }[] = [
  { value: 'laptop', icon: Laptop },
  { value: 'monitor', icon: Monitor },
  { value: 'keyboard', icon: Keyboard },
  { value: 'mouse', icon: Mouse },
  { value: 'smartphone', icon: Smartphone },
  { value: 'headphones', icon: Headphones },
  { value: 'plug-zap', icon: PlugZap },
  { value: 'tablet', icon: Tablet },
  { value: 'printer', icon: Printer },
  { value: 'battery-charging', icon: BatteryCharging },
  { value: 'cable', icon: Cable },
  { value: 'usb', icon: Usb },
  { value: 'hard-drive', icon: HardDrive },
  { value: 'webcam', icon: Webcam },
  { value: 'router', icon: Router },
  { value: 'network', icon: Network },
  { value: 'wifi', icon: Wifi },
  { value: 'server', icon: Server },
  { value: 'zap', icon: Zap },
  { value: 'projector', icon: Projector },
  { value: 'tv', icon: Tv },
  { value: 'presentation', icon: Presentation },
  { value: 'camera', icon: Camera },
  { value: 'video', icon: Video },
  { value: 'mic', icon: Mic },
  { value: 'speaker', icon: Speaker },
  { value: 'scan-line', icon: ScanLine },
  { value: 'barcode', icon: Barcode },
  { value: 'armchair', icon: Armchair },
  { value: 'lamp', icon: Lamp },
  { value: 'briefcase', icon: Briefcase },
  { value: 'watch', icon: Watch },
  { value: 'wrench', icon: Wrench },
  { value: 'hard-hat', icon: HardHat },
  { value: 'glasses', icon: Glasses },
  { value: 'antenna', icon: Antenna },
  { value: 'credit-card', icon: CreditCard },
  { value: 'globe', icon: Globe },
  { value: 'id-card', icon: IdCard },
  { value: 'key', icon: Key },
  { value: 'badge', icon: Badge },
  { value: 'car', icon: Car },
  { value: 'fuel', icon: Fuel },
  { value: 'parking-square', icon: ParkingSquare },
  { value: 'shield', icon: Shield },
  { value: 'cloud', icon: Cloud },
  { value: 'mail', icon: Mail },
  { value: 'receipt', icon: Receipt },
  { value: 'file-signature', icon: FileSignature },
  { value: 'scroll-text', icon: ScrollText },
  { value: 'shield-check', icon: ShieldCheck },
  { value: 'box', icon: Box },
  { value: 'battery', icon: Battery },
  { value: 'lock', icon: Lock },
  { value: 'file-text', icon: FileText },
  { value: 'users', icon: Users }
];

const iconMap = new Map(categoryIconOptions.map(item => [item.value, item.icon]));

export function CategoryIcon({ icon, size = 16 }: { icon?: string | null; size?: number }) {
  const Icon = (icon && iconMap.get(icon)) || Package;
  return <Icon size={size} />;
}
